
[notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: pip install --upgrade pip
cloning test-rl-leaderboard
Creating virtual env...
Scoring model...
/home/runner/work/rl-leaderboard/rl-leaderboard/test-rl-leaderboard/.virtualenv/lib/python3.8/site-packages/gym/envs/registration.py:307: DeprecationWarning: The package name gym_minigrid has been deprecated in favor of minigrid. Please uninstall gym_minigrid and install minigrid with `pip install minigrid`. Future releases will be maintained under the new package name minigrid.
  fn()
cloning conservation-vanilla
Creating virtual env...
Scoring model...
Traceback (most recent call last):
  File "../score_model.py", line 2, in <module>
    from stable_baselines3 import A2C, PPO, SAC, DDPG, TD3, DQN, HER
ModuleNotFoundError: No module named 'stable_baselines3'
Error with score_model.py for https://github.com/tim08526/conservation-vanilla
cloning rl-leaderboard-output
Creating virtual env...
Scoring model...
Traceback (most recent call last):
  File "../score_model.py", line 2, in <module>
    from stable_baselines3 import A2C, PPO, SAC, DDPG, TD3, DQN, HER
ModuleNotFoundError: No module named 'stable_baselines3'
Error with score_model.py for https://github.com/Brandons42/rl-leaderboard-output
cloning rl-tipping-points
Creating virtual env...
Scoring model...
Traceback (most recent call last):
  File "../score_model.py", line 2, in <module>
    from stable_baselines3 import A2C, PPO, SAC, DDPG, TD3, DQN, HER
ModuleNotFoundError: No module named 'stable_baselines3'
Error with score_model.py for https://github.com/cboettig/rl-tipping-points
cloning rl-fishing-test
Creating virtual env...
Scoring model...
Traceback (most recent call last):
  File "../score_model.py", line 2, in <module>
    from stable_baselines3 import A2C, PPO, SAC, DDPG, TD3, DQN, HER
ModuleNotFoundError: No module named 'stable_baselines3'
Error with score_model.py for https://github.com/mchxo/rl-fishing-test
cloning carl-climate-agents
Creating virtual env...
Scoring model...
Traceback (most recent call last):
  File "../score_model.py", line 2, in <module>
    from stable_baselines3 import A2C, PPO, SAC, DDPG, TD3, DQN, HER
ModuleNotFoundError: No module named 'stable_baselines3'
Error with score_model.py for https://github.com/cboettig/carl-climate-agents/
cloning rl-leaderboard-output-fishing-v0
Error: Command '['/home/runner/work/rl-leaderboard/rl-leaderboard/rl-leaderboard-output-fishing-v0/.virtualenv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
Creating virtual env...
./run.sh: line 27: .virtualenv/bin/activate: No such file or directory
Scoring model...
Traceback (most recent call last):
  File "../score_model.py", line 4, in <module>
    import gym
ModuleNotFoundError: No module named 'gym'
Error with score_model.py for https://github.com/Brandons42/rl-leaderboard-output-fishing-v0
./run.sh: line 38: deactivate: command not found
cloning test-rl-leaderboard1
fatal: write error: No space left on device
fatal: fetch-pack: invalid index-pack output
./run.sh: line 22: cd: test-rl-leaderboard1: No such file or directory
Error: Command '['/home/runner/work/rl-leaderboard/rl-leaderboard/.virtualenv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
Creating virtual env...
./run.sh: line 27: .virtualenv/bin/activate: No such file or directory
Scoring model...
python: can't open file '../score_model.py': [Errno 2] No such file or directory
Error with score_model.py for https://github.com/mlap/test-rl-leaderboard1
./run.sh: line 38: deactivate: command not found
cloning millie-conservation-agents
fatal: write error: No space left on device
fatal: fetch-pack: invalid index-pack output
./run.sh: line 22: cd: millie-conservation-agents: No such file or directory
Error: Command '['/home/runner/work/rl-leaderboard/.virtualenv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
Creating virtual env...
./run.sh: line 27: .virtualenv/bin/activate: No such file or directory
Requirement already satisfied: stable_baselines3 in /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages (2.2.1)
Requirement already satisfied: sb3_contrib in /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages (2.2.1)
Requirement already satisfied: gymnasium<0.30,>=0.28.1 in /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages (from stable_baselines3) (0.29.1)
Requirement already satisfied: numpy>=1.20 in /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages (from stable_baselines3) (1.24.4)
Requirement already satisfied: torch>=1.13 in /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages (from stable_baselines3) (2.2.0)
Requirement already satisfied: cloudpickle in /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages (from stable_baselines3) (3.0.0)
Requirement already satisfied: pandas in /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages (from stable_baselines3) (2.0.3)
Requirement already satisfied: matplotlib in /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages (from stable_baselines3) (3.7.4)
Requirement already satisfied: typing-extensions>=4.3.0 in /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages (from gymnasium<0.30,>=0.28.1->stable_baselines3) (4.9.0)
Requirement already satisfied: farama-notifications>=0.0.1 in /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages (from gymnasium<0.30,>=0.28.1->stable_baselines3) (0.0.4)
Requirement already satisfied: importlib-metadata>=4.8.0 in /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages (from gymnasium<0.30,>=0.28.1->stable_baselines3) (7.0.1)
Requirement already satisfied: filelock in /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages (from torch>=1.13->stable_baselines3) (3.13.1)
Requirement already satisfied: sympy in /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages (from torch>=1.13->stable_baselines3) (1.12)
Requirement already satisfied: networkx in /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages (from torch>=1.13->stable_baselines3) (3.1)
Requirement already satisfied: jinja2 in /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages (from torch>=1.13->stable_baselines3) (3.1.3)
Requirement already satisfied: fsspec in /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages (from torch>=1.13->stable_baselines3) (2024.2.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages (from torch>=1.13->stable_baselines3) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages (from torch>=1.13->stable_baselines3) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages (from torch>=1.13->stable_baselines3) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==8.9.2.26 in /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages (from torch>=1.13->stable_baselines3) (8.9.2.26)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages (from torch>=1.13->stable_baselines3) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages (from torch>=1.13->stable_baselines3) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages (from torch>=1.13->stable_baselines3) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages (from torch>=1.13->stable_baselines3) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages (from torch>=1.13->stable_baselines3) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.19.3 in /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages (from torch>=1.13->stable_baselines3) (2.19.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages (from torch>=1.13->stable_baselines3) (12.1.105)
Requirement already satisfied: triton==2.2.0 in /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages (from torch>=1.13->stable_baselines3) (2.2.0)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages (from nvidia-cusolver-cu12==11.4.5.107->torch>=1.13->stable_baselines3) (12.3.101)
Requirement already satisfied: contourpy>=1.0.1 in /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages (from matplotlib->stable_baselines3) (1.1.1)
Requirement already satisfied: cycler>=0.10 in /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages (from matplotlib->stable_baselines3) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages (from matplotlib->stable_baselines3) (4.47.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages (from matplotlib->stable_baselines3) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages (from matplotlib->stable_baselines3) (23.2)
Requirement already satisfied: pillow>=6.2.0 in /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages (from matplotlib->stable_baselines3) (10.2.0)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages (from matplotlib->stable_baselines3) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages (from matplotlib->stable_baselines3) (2.8.2)
Requirement already satisfied: importlib-resources>=3.2.0 in /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages (from matplotlib->stable_baselines3) (6.1.1)
Requirement already satisfied: pytz>=2020.1 in /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages (from pandas->stable_baselines3) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages (from pandas->stable_baselines3) (2023.4)
Requirement already satisfied: zipp>=0.5 in /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages (from importlib-metadata>=4.8.0->gymnasium<0.30,>=0.28.1->stable_baselines3) (3.17.0)
Requirement already satisfied: six>=1.5 in /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages (from python-dateutil>=2.7->matplotlib->stable_baselines3) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages (from jinja2->torch>=1.13->stable_baselines3) (2.1.5)
Requirement already satisfied: mpmath>=0.19 in /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages (from sympy->torch>=1.13->stable_baselines3) (1.3.0)

[notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: pip install --upgrade pip
Scoring model...
python: can't open file '../score_model.py': [Errno 2] No such file or directory
Error with score_model.py for https://github.com/milliechapman/millie-conservation-agents
./run.sh: line 38: deactivate: command not found
